### PR TITLE
Added DESI.ipynb corrections

### PR DESCRIPTION
**Pull request by alxogm**
starting PR from @ChavezUriel

### CODE REVIEW

**Comment by michaelJwilson** [comment]
This is to be scrubbed?

**Comment by alxogm** [comment]
> This is to be scrubbed?

Yes, I had some changes already implemented, but I need to go over them again, I'll try to finish it today.

**Comment by alxogm** [comment]
This is ready to merge, change is really minimal, but I had forgotten to review it.

**Review by michaelJwilson — APPROVED** [review]

**Comment by michaelJwilson** [comment]
Thanks!

**Pull request merged**
