### PR TITLE
Update colab.py

### PR DESCRIPTION
**Pull request by alxogm**
I've moved up the line to append the desihigh directory to the PATH so that the second try of `import desihigh` is succesful. And have also made a last `os.chdir` to the desihigh directory so that later on figures and files can be loaded without changing the paths. 

Another fix I'd suggest is to rename the script `colab.py` to something like `set_colab.py` or `desihigh_colab.py` or something else , becase there seems to be  `colab` library, that is loaded if you don't use the one from desihigh repository. See image from an import in a clean Colab notebook 
Captura de Pantalla 2022-01-25 a la(s) 22 54 08

### CODE REVIEW

**Comment by alxogm** [comment]
Another comment to consider:

I think the script works great for  saving a copy of the repository in Google drive without having to explain git clone... 

However, and maybe its just me doing something in the wrong way,  when opening a desihigh notebook, either directly in colab or from the copy of the repository that is save in Drive, those are open in "new" machines that do not inherit the environment variables, nor the Drive is mounted automatically, therefore you have to make `import colab` again, but you don't have access to the `colab.py` script unless you copy it again, which I think is a bit confusing...  Alternatively, and I think I still find this option simpler,  you can manually mount the `MyDrive/desihigh` directory and set the desihigh path. 

In any case I think each notebook should have a set of commented lines that one would uncomment when working on Colab instead of Binder (or some `if..else/try..except` statement)

**Comment by michaelJwilson** [comment]
Agreed on the name change then.  Let me think about the sys path, the idea was to first cd to the right directory first and see if you had what you needed.  If not, get what you need.  You're kind of assuming the answer. 

I appreciate the problem with colab.py, it's not a user error.  Commenting if/else is a bit messy / fragile for me, I'd like to get something that's a simple import and does the job for them.  The answer isn't obvious to me though, maybe there's library that runs something sort of customisation of imports.  I guess what we want is 'import desihigh' if that fails, run the code in colab.py, but in a way not visible to the students.

**Comment by michaelJwilson** [comment]
One possibility to test:
https://stackoverflow.com/questions/35935670/share-variables-between-different-jupyter-notebooks

where things always start from colab.ipnb, we store and then open the next notebook.

**Comment by michaelJwilson** [comment]
store doesn't work on colab. 

The screenshot below shows how to mount the drive via clicking. 

image

Required changes are colab.py stays the same and is always run once via the notebook for any student working on colab. 
We then add import sys; sys.path.append('/content/drive//MyDrive//desihigh/') to the start of all nbs.  This is essentially a null op for anyone not on colab, so no need for comments. 

Happy with that?

**Comment by alxogm** [comment]
> We then add import sys; sys.path.append('/content/drive//MyDrive//desihigh/') to the start of all nbs. This is essentially a null op for anyone not on colab, so no need for comments.

If you are sure this does not causes issues in binder, then I'm fine with that. But, for displaying the images, as they are being called, I think it was not enough to append desihigh to the path, I think it required to change the directory, i.e. os.chdir(/content/drive//MyDrive//desihigh/) .  But I can test that while fixing the notebooks that are not displaying the images correctly.

**Comment by alxogm** [comment]
For reasons I don't really understand, sys.append.path sometimes works and others it don't. It seems if I open a notebook from your link https://www.githubtocolab.com/michaelJwilson/desihigh, things work, even the loading of the images. But when I open the notebooks directly from myDrive, after cloning, mounting the drive, etc,  things don't work... so the changes I've implemented should always work.

**Comment by alxogm** [comment]
It seems I cleared the relevant lines in the notebook to mount the Drive and change directory. As mentioned above, sys.path.append is not always working, but changing directory does. The issue I think os.chdir will make binder fails, so I think the IF I added is the best I can get. I'd suggest we merge and see how it works. 

Note that in Colab.ipynb I moved the image to a few cells below, because it can not be displayed until we clone de repository and mount the drive. Alternatively we could copy it the same way as the colab.py script, if you really want to display it at the begining, (or load it from a http address, I think that should also work)

**Pull request closed without merging**
